### ISSUE TITLE
Support 8 & 24 bit color

### ISSUE THREAD

**Issue by naturalethic** [jorgebucaran/colorette#27]
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

Additionally, generators for colors say,

`const mauve = colorette('#b784a7')`

Maybe theming too.

**Comment by jorgebucaran** [comment]
Interesting idea. There are a few ways to do this. I'll experiment a bit.

@naturalethic What is theming?

**Comment by jorgebucaran** [comment]
Generating the ANSI sequences is easy. Downsampling 24-bit colors colors on terminals that don't support 24-bit color, e.g. `Terminal.app`, is hard.

Chalk does this using `color-convert` and `supports-color`. 

`color-convert` can convert a 24-bit color to 16-bit, 8-bit, etc., and `supports-color` check for specific terminal color support. Color detection might not be 100% reliable [according to this](https://gist.github.com/XVilka/8346728#detection), but it works well in practice. 

I'm not going to incorporate `color-convert` or `supports-color` to Colorette at this time, but I can provide the following new named exports `ansi16`, `ansi256`, and `trueColor`. You can use them  with `color-convert` to generate additional color functions.

Here is an example I put together to show how that could potentially look like:

```jsx
const { ansi16, ansi256, ansi16m } = require("colorette")

const convert = require("color-convert")
const supportsTruecolor = require("supports-color").stdout.has16m
const HEX_COLOR = "#1557ff"

const fg16 = ansi16(convert.hex.ansi16(HEX_COLOR))
const bg16 = ansi16(convert.hex.ansi16(HEX_COLOR), true)
console.log(fg16(HEX_COLOR), bg16(HEX_COLOR), "in 16 colors")

if (supportsTruecolor) {
  const fgTrue = ansi16m(...convert.hex.rgb(HEX_COLOR))
  const bgTrue = ansi16m(...convert.hex.rgb(HEX_COLOR), true)
  console.log(fgTrue(HEX_COLOR), bgTrue(HEX_COLOR), "in truecolor")
} else {
  const fg256 = ansi256(convert.hex.ansi256(HEX_COLOR))
  const bg256 = ansi256(convert.hex.ansi256(HEX_COLOR), true)
  console.log(fg256(HEX_COLOR), bg256(HEX_COLOR), "in 256 colors")
}
```

**Comment by jorgebucaran** [comment]
Generating the ANSI sequences is easy. Downsampling 24-bit color on terminals that don't support 24-bit color, e.g. `Terminal.app` not so much.

Chalk does this using `color-convert` and `supports-color`.

`color-convert` can convert a 24-bit color to 16-bit, 8-bit, etc., and `supports-color` allow you to check for specific terminal color support. Color detection might not be 100% reliable [according to this](https://gist.github.com/XVilka/8346728#detection), but it seems to work well.

I'm not going to incorporate `color-convert` or `supports-color` as a dependency to Colorette at this time, but I can provide the following [new named exports `ansi16`, `ansi256`, and `rgb`](https://github.com/jorgebucaran/colorette/blob/f1f31e4bcd95eb40bcf83694a54e15c4a86dca3f/index.js#L83-L85), which you can use with `color-convert` to generate additional color functions.

Here is an example to show you how that could potentially look like:

## Example

- **`index.js`**

  ```jsx
  const { hex } = require("./utils/hex")
  const mauve = hex("#b784a7")

  console.log(mauve("Mauve!"))
  ```

- **`./utils/hex.js`**

  ```jsx
  const { stdout } = require("supports-color")
  const { hex } = require("color-convert")
  const { rgb, ansi256, ansi16 } = require("colorette")

  module.exports = {
    hex: color =>
      stdout
        ? stdout.has16m
          ? rgb(...hex.rgb(color))
          : ansi256(hex.ansi256(color))
        : ansi16(hex.ansi16(color))
  }
  ```

## Result

- Terminal.app

  ![](https://user-images.githubusercontent.com/56996/47256328-3cddb080-d4b9-11e8-8a73-d7c1caba17f2.png)

- iTerm.app (v3.2.3)

  ![](https://user-images.githubusercontent.com/56996/47256327-3c451a00-d4b9-11e8-9241-4c617fef41b5.png)


cc @naturalethic

**Comment by naturalethic** [comment]
Great stuff!  Regarding theming upon some though there's nothing you'd need to provide.  People can just put together any kind of color scheme they like and provide a small library if they want.  Terminals themselves can theme the standard 16 colors.

**Comment by jorgebucaran** [comment]
@naturalethic Thanks! Maybe I can improve this a bit more. I'll experiment more.

**Comment by jorgebucaran** [comment]
@naturalethic I played a bit more with it and whittled it down to this.

```jsx
const color = require("colorette")
const { rgb, ansi256, ansi16  } = require("color-convert").hex
const hex = color.generate({ rgb, ansi256, ansi16 })

const mauve = hex("#b784a7")
console.log(mauve("Mauve"))
```

Now, compare it to what I posted above. Which one is better?

```jsx
const { stdout } = require("supports-color")
const hexTo = require("color-convert").hex
const { rgb, ansi256, ansi16 } = require("colorette")

const hex = color =>
    stdout
      ? stdout.has16m
        ? rgb(...hexTo.rgb(color))
        : ansi256(hexTo.ansi256(color))
      : ansi16(hexTo.ansi16(color))

const mauve = hex("#b784a7")
console.log(mauve("Mauve"))
```

**Comment by naturalethic** [comment]
Seems you could just do this:
```javascript
const color = require("colorette")
const hex = color.generate(require("color-convert").hex)
```

**Comment by naturalethic** [comment]
Or perhaps you could document that the end user must add `color-covert` to their packages if they want `hex`, then just provide the `hex` method on your library, which will give a friendly error if the `color-convert` package isn't present.

**Comment by jorgebucaran** [comment]
@naturalethic Opps, I did it again. https://github.com/jorgebucaran/colorette/pull/31



That adds built-in 24-bit color support.

```jsx
const { hex } = require("colorette")
const mauve = hex("#b784a7")

console.log(mauve("TrueColor"))
```
```console
\u001b[38;2;183;132;167mTrueColor\u001b[39m
```



###### Terminal.app

> Reduced to 8-bit in terminals without TrueColor support.

<img width="595" alt="screen shot 2018-10-26 at 1 00 24" src="https://user-images.githubusercontent.com/56996/47514109-8ca5e880-d8ba-11e8-82a7-8fb76293efa3.png">

###### iTerm.app (v3)

<img width="595" alt="screen shot 2018-10-26 at 1 00 01" src="https://user-images.githubusercontent.com/56996/47514107-8ca5e880-d8ba-11e8-9cf2-3e1d68d319ab.png">

**Comment by jorgebucaran** [comment]
@naturalethic Me too. Thoughts? :)

**Comment by jorgebucaran** [comment]
> @naturalethic  Does the performance hold up even in 24 bit?

Yes, it does. The color factory functions `hex`, `bgHex`, `rgb` or `bgRgb` do extra work to produce a new color function, but once you've created it, the resulting function will perform exactly as any of the 16 built-in ones.

## Example 

Import a built-in color function and a color factory function.

```js
const { red, hex } = require("colorette")
```

Derive a new color function.

```js
const trueRed = hex("#ff0000")
```

From this point on you can expect the same performance out from `trueRed` and `red`.

**Comment by jorgebucaran** [comment]
I want to focus on the core functionality of this package, and simply not address 8~24 bit color at this time.
