### ISSUE TITLE
these aren't actually ansi sequences

### ISSUE THREAD

**Issue by StoneCypher** [jorgebucaran/colorette#33]
these are vt-102 codes.  ansi sequences are a partial subset.  lots of the things you support don't occur in ansi

**Comment by StoneCypher** [comment]
ansi sequences are mostly about cursor movement, control page setting, blanking, bitmap replacement, and other stuff most people don't even remember exists and that isn't supported by any of these libraries (or, for that matter, any windows computer)

unless you're targetting dos (pro tip: there is no dos node edition, soooo, maybe it's hyperterminal doing telnet over slip/ppp?) there is never a reason to make a node ansi library

**Comment by jorgebucaran** [comment]
@StoneCypher Terminology can be tricky. What do you suggest we change the title to?

Colorette is a Node.js library for colorizing text using ~~ANSI escape sequences~~ ANSI escape codes?

**Comment by StoneCypher** [comment]
vt codes, or vt-102 codes, as you prefer

**Comment by jorgebucaran** [comment]
@StoneCypher What about:

- terminal color codes
- terminal color sequences
- terminal CSI codes

**Comment by jorgebucaran** [comment]
VT Codes has poor marketability or discoverability. Here are other alternatives I could think of:

- ANSI codes 
- terminal color codes
- terminal color sequences
- terminal CSI codes

I'll try to figure something out for the next release.

**Comment by NetOperatorWibby** [comment]
Why not

> Colorette is a Node.js library for colorizing text in terminals

?

**Comment by jorgebucaran** [comment]
@NetOperatorWibby Yep, why not indeed! Let me see what I can do! 😄
