### ISSUE TITLE
Expose start/end codes for more custom use

### ISSUE THREAD

**Issue by n1kk** [jorgebucaran/colorette#34]
Would it be possible to expose the sequences themself as something like `redStart`/`redEnd` or `red.start`/`red.end` to give users ability to set color for all the upcoming output until manually changed ?

I had a few cases where I was receiving data for output asynchronously from several child processes and wanted to colorize it by app state. It was a bit tedious to wrap each output into colorizing calls and just made code cluttered, more complicated and harder to read.

So the use case I imagine would be 
```javascript
const { green, yellow, grey, red } = require("colorette");
console.log(green.start)
// ... some regular state output
console.log(yellow.start)
// ... some import/sync/rebuild state output in yellow
console.log(yellow.end)
// regular output continues with green
console.log(grey.start)
// ... some cleanup state output in yellow
console.log(grey.end)

process.on('uncaughtException', function (err) {
  console.log(red(err)); // errors printed out in red
})
```

**Comment by jorgebucaran** [comment]
> Would it be possible to expose the sequences themselves as something like redStart/redEnd or red.start/red.end to give users the ability to set the color for all the upcoming output until manually changed?

Yes, it would be possible. But is it worth it? I'm open to discussing it.

> I had a few cases where I was receiving data for output asynchronously from several child processes and wanted to colorize it by app state. It was a bit tedious to wrap each output into colorizing calls and just made code cluttered, more complicated and harder to read.

Can you show me some code? I'd like to see what is it you call cluttered and more complicated to use.

**Comment by jorgebucaran** [comment]
No response. Closing.
