### ISSUE TITLE
Support for "link" modifier

### ISSUE THREAD

**Issue by frenzzy** [jorgebucaran/colorette#37]
I really like a minimalism of this library, but I also have to create clickable links in terminal.
I thought maybe it is possible to add one more very useful modifier?
```js
const { link } = require("colorette")
console.info(`App is now running on ${link('http://localhost:3000')}`)
```
refs:
- https://github.com/sindresorhus/ansi-escapes#linktext-url
- https://github.com/sindresorhus/terminal-link

**Comment by jorgebucaran** [comment]
@frenzzy This isn't hard to implement, but colorette might not be the right place for this feature. Does chalk export a `link` function/method?

**Comment by frenzzy** [comment]
`Chalk` does not export something similar but they have a [Related](https://github.com/chalk/chalk#related) section in its readme with a link to [`terminal-link`](https://github.com/sindresorhus/terminal-link) project.

I understand that this function is weakly related to the main purpose of the package (based on its name). My idea is that the `link` is the only missing feature which allows to make beauty and useful terminal programs and probably it is enough to just add one more line to the source code still keeping this package small and dependencies free. Of course I can use two different npm packages for this purposes, but if I could use just one it would be awesome :)

**Comment by jorgebucaran** [comment]
I can't recall what my reasoning was, but I'm thinking that perhaps we should include this. There's already **bold**, _italics_, etc.

**Comment by jorgebucaran** [comment]
Turns out this doesn't really work on macOS Terminal. Otherwise, support is pretty good. Maybe someday.
