### ISSUE TITLE
Unable to use in Jest tests

### ISSUE THREAD

**Issue by vladshcherbin** [jorgebucaran/colorette#38]
Hey 👋 

I'm trying to test console output in [jest](https://jestjs.io/) tests, but it seems `colorette` doesn't work there. After looking at source code and [enabled variable](https://github.com/jorgebucaran/colorette/blob/1.1.0/index.js#L8) I found that `process.stdout.isTTY` returns `undefined` which results in disabled state.

I've also checked chalk and it's working in the same tests.

Maybe you have an idea how this can be fixed?

Thank you

**Comment by jorgebucaran** [comment]
@vladshcherbin No, but if you can put together an example project, I may be able to look at it. And if you can figure it out, send me a PR. 👋

**Comment by vladshcherbin** [comment]
@jorgebucaran As it sometimes happens, I've created a sample project and it works there. :shit:

Next, I've checked it again in my project and it works too. However, not every time, in watch mode it sometimes works and sometimes not.

All comes to `process.stdout.isTTY` which is sometimes `undefined` and sometimes `true`. Maybe you know why can this be happening since [there is a check for it](https://github.com/jorgebucaran/colorette/blob/1.1.0/index.js#L8)?

**Comment by jorgebucaran** [comment]
@vladshcherbin Have you tried directly setting `options.enabled` to override its initial value? 🤔

**Comment by vladshcherbin** [comment]
@jorgebucaran seems to be working with `options.enabled` 👍 Good enough as a workaround, what do you think?

**Comment by jorgebucaran** [comment]
@vladshcherbin Sounds good! 🙌
