### ISSUE TITLE
Consider providing a tree-shakeable ESM build

### ISSUE THREAD

**Issue by lukastaegert** [jorgebucaran/colorette#39]
I know colorette is already very small, but its architecture would allow for even smaller and more efficient output when bundling colorette if there was an ESM build that provided named exports. The current approach of putting everything on module.exports is unfortunately not suitable for tree-shaking as bundlers usually cannot tear that object apart.

If you do not want to maintain two builds, you could also do the conversion automatically with a tool like Rollup 😉

**Comment by jorgebucaran** [comment]
That could be interesting! 😄

**Comment by silverwind** [comment]
@lukastaegert would this format be tree-shakeable?

```` js
module.exports.green = ...
module.exports.red = ...
````

**Comment by jorgebucaran** [comment]
@silverwind Yes, as it's essentially the same as using a named `export`. That's essentially what we're currently using, no?

**Comment by silverwind** [comment]
It's equivalent, with the benefit that the linewise style should be much easier to parse for bundlers. Also, it'll be a breeze to convert that style to ESM eventually.

**Comment by lukastaegert** [comment]
Note sure about `module.exports.green =`, that I would need to check, but I definitely know that the equivalent assignment `exports.green =` will be converted to treeshakeable named exports by Rollup. Which would be perfect for me 😉. Also this would be marginally faster as there is one less property lookup in the assignment.

**Comment by jorgebucaran** [comment]
@lukastaegert What is it exactly about the current implementation that makes it difficult or impossible to tree-shake. I'm happy to move things around in order to enable this.

**Comment by lukastaegert** [comment]
Assigning something to `module.exports` is usually interpreted as default exporting it. Even though in your case it is an object, our current logic is not intelligent enough to derive named exports from the object literal. Which it could, but this would be quite a bit more work on our side and I hate to admit, rollup-plugin-commonjs is already some kind of mess. Assignments to properties of `exports`, on the other hand, is well detected and can be easily rewritten.

**Comment by silverwind** [comment]
I hope `module.exports` is supported because it's pretty ingrained in node developers, partly because of [this post](https://blog.tableflip.io/the-difference-between-module-exports-and-exports/).

**Comment by wopian** [comment]
CommonJS `module.exports` doesn't support ESM named exports - you only get access to the default export (an object here). It'll throw a syntax error if you try it.

```
// index.js [Node 14]
import { bold, red } from 'colorette'
/* SyntaxError: The requested module 'colorette' is expected to be of type CommonJS, 
    which does not support named exports. CommonJS modules can be imported by 
    importing the default export.
    For example:
    import pkg from 'colorette'
    const { bold, red } = pkg
*/
```

You're able to target ESM import and CommonJS require by using the `exports` field in `package.json` for Node 12 and above. https://nodejs.org/api/esm.html#esm_conditional_exports

**Comment by jorgebucaran** [comment]
I'd love to migrate colorette to Node >=14 and drop support for older nodes, but I don't think everyone is ready for that. But we could support both worlds and I'd be willing to maintain them until the time is right to let go of require.

**Comment by wopian** [comment]
@jorgebucaran you can support both and be backwards compatible by keeping `main` as `index.js` and add the following field in `package.json`:

```json
exports: {
  "./package.json": "./package.json",
  ".": {
    "import": "./index.esm.js",
    "require": "./index.js"
  },
  "./index.js": {
    "import": "./index.esm.js",
    "require": "./index.js"
  },
  "./index.esm.js": {
    "import": "./index.esm.js",
    "require": "./index.js"
  }
}
```

This would only leave named exports "broken" in Node 10 (EOL April 2021) environments using native ESM import syntax which requires the `--experimental-modules` flag and `.mjs` to use.

**Comment by jorgebucaran** [comment]
Thanks for the info, @wopian. Do you reckon that is the best (most minimal) way to accomplish the job?

**Comment by ai** [comment]
[`dual-publish`](https://github.com/ai/dual-publish/) can automatically convert CJS module to dual CJS/ESM module on deploy.

You just need to change `module.exports` to:

```js
const italic: init(3, 23)

module.exports = { italic, … }
```

I used in very popular projects like [`nanoid`](https://github.com/ai/nanoid/) and [`dual-publish`](https://github.com/ai/dual-publish/blob/master/test/index.test.js) has many edge cases in tests (like React Native, different web bundlers, etc).

I can send a PR for you.
