### ISSUE TITLE
Error: No valid exports main found 

### ISSUE THREAD

**Issue by vsehgal1** [jorgebucaran/colorette#46]
OS: Ubuntu: 18.04
Node Version: 13.6.0
Colorette Version: 1.2.1

After the version update anytime I try to `npm start` I face the following issue:
`Error: No valid exports main found for './node_modules/colorette'`

Am I missing something?
Thank you

**Comment by vsehgal1** [comment]
Works when I downgrade to 1.2.0

**Comment by twalton83** [comment]
Also seeing this issue  when I use create-react-app.

**Comment by ok200paul** [comment]
https://twitter.com/jorgebucaran/status/1279802683264626688 - update to node >=13.7.0 :)

**Comment by seanmwfried** [comment]
> 
> 
> https://twitter.com/jorgebucaran/status/1279802683264626688 - update to node >=13.7.0 :)

Updating Node fixed this for me. 
`nvm install latest` put me on 14.5.0 and my vue dev server launched with no problem this time.

**Comment by twalton83** [comment]
> https://twitter.com/jorgebucaran/status/1279802683264626688 - update to node >=13.7.0 :)

Thanks for the heads up! Works great.

**Comment by jorgebucaran** [comment]
@vsehgal1 Glad you figured it out @/all. Some versions in the Node 13.x range have buggy ES module support or need `--experimental-modules` in the command line, so I suggest you upgrade to Node >=13.7.
