### ISSUE TITLE
Cannot be used with node v13

### ISSUE THREAD

**Issue by zhengxs2018** [jorgebucaran/colorette#48]
system versions

 - mac os
 - window10

node versions:

 - v13.3.0

module as a production dependency of autoprefixer, not available in node v13.3.0

Works fine in node v12 and v14

![image](https://user-images.githubusercontent.com/7506913/86740216-0cf98680-c069-11ea-8316-d88d065ad66d.png)

**Comment by jorgebucaran** [comment]
@zhengxs2018 Some versions in the Node 13.x range have buggy ES module support or need --experimental-modules in the command line, so I suggest you upgrade to Node 13.7 if you want to continue using 13 for some reason, or better yet >=14 if you can. 👋

Related https://github.com/jorgebucaran/colorette/issues/46
