### ISSUE TITLE
No valid exports main found when compile

### ISSUE THREAD

**Issue by songeastchang** [jorgebucaran/colorette#54]
Failed to compile.

./src/index.css
Error: No valid exports main found for 'd:\myapp\node_modules\autoprefixer\node_modules\colorette'

main method is missing when running "npm run build"

**Comment by jorgebucaran** [comment]
@songeastchang Could be a dupe of #48. See https://github.com/jorgebucaran/colorette/issues/48#issuecomment-654669713. 

Let me know if that solves it for you. 👋
