### ISSUE TITLE
[colorette v1.4] `tty && tty.isatty(1)` breaks in vite HMR mode

### ISSUE THREAD

**Issue by LeoniePhiline** [jorgebucaran/colorette#67]
Hi!

In vite HMR mode, `require('tty')` returns a mock module, which is auto-defined as:

```javascript
// browser-external:tty
var tty_exports = {};
__export(tty_exports, {
  default: () => tty_default
});
var tty_default;
var init_tty = __esm({
  "browser-external:tty"() {
    init_define_process_env();
    tty_default = new Proxy({}, {
      get() {
        throw new Error('Module "tty" has been externalized for browser compatibility and cannot be accessed in client code.');
      }
    });
  }
});
```

Therefore, the check `tty && tty.isatty(1)` (`isCompatibleTerminal`) fails with "TypeError: tty.isatty is not a function".

I can't help by disabling via `process.env.NO_COLOR`, because `isCompatibleTerminal` is eagerly evaluated, no matter if `NO_COLOR` is set or not.

Could you please consider:

1. Aborting without further checks if `process.env.NO_COLOR` is set.
2. Or lazily evaluating `isCompatibleTerminal` only after checking for `!isDisabled`.

Thank you!

**Comment by jorgebucaran** [comment]
Thanks. How would I go about reproducing your environment to test this myself?

**Comment by LeoniePhiline** [comment]
- Create a new vite project. In my case vie & typescript (vue-ts preset)
- Install sanitize-html, import it in a vue component to use in the browser, and sanitize some html (or any string) with it
- Start vite HMR mode (npm run dev)
- Open in the Browser

what happens:
Browser pulls es modules. Sanitize-html imports postcss to parse your html string into an AST. Postcss pulls in colorette 1.4. Colorette crashes the app with tty.isatty(1)

**Comment by jorgebucaran** [comment]
Gotcha, thanks! I believe updating to the latest Colorette should fix it.

**Comment by jorgebucaran** [comment]
`2.0.6` includes a check to make sure `env` exists. We might be able to remove this in the future too.
