### ISSUE TITLE
Upgrading to 2.0.0

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/colorette#70]
If you're upgrading from `1.x`:

- Top-level color functions will produce color always now. 
  - To enable or disable color, there's a new `createColors(options)` that returns an object with all the available color functions. Terminal support is auto-detected, but you can override it via `options.useColor`.
- The previously available `options.enabled` has been removed in favor of `createColors(options)`.
- There's a new `isColorSupported` constant export. 
  - `true` if the terminal supports color, `false` otherwise.

If you need color output automatically enabled or disabled based on terminal support, use `createColors` to get colors instead of importing them directly from `colorette`.

```js
import { createColors } from "colorette"

const { blue } = createColors()

console.log(blue("Hey"))
```

If you were previously using `options.enabled` to override automatic color detection, use `{ useColor }` instead.

```js
import { createColors } from "colorette"
 ...
const { blue } = createColors({ useColor: myOptions.enabled })
```

For many use-cases, Colorette will continue to work as-is. Don't care about terminal support? You don't need to do anything.

```js
import { blue } from "colorette"

console.log(blue("Always blue! Always blue! ..."))
```

**Comment by kibertoad** [comment]
@jorgebucaran What's the rationale behind default colouring functions being enabled by default, rather than relying on auto-detect by default, btw?

**Comment by jorgebucaran** [comment]
Purity. I always found the previous behavior surprising and unreliable.

With `isColorSupported` you can implement a toggling mechanism yourself if you wish, or just use `createColors()` as our out-of-the-box solution.

**Comment by jorgebucaran** [comment]
This may be causing more trouble than I thought for existing users, so perhaps we should bring back auto-detection for the simplest use case instead. I'm not a huge fan of the approach, but I can live with it.
