### ISSUE TITLE
tty.isatty is not a function

### ISSUE THREAD

**Issue by from-nibly** [jorgebucaran/colorette#74]
I'm using sanitize-html in the browser which uses postcss which uses this.

When postcss imports collorette it fails on the line checking for isCompatibleTerminal

A quick fix would be to switch to the following by adding a check that `tty.isatty` exists before calling it.

```js
const isCompatibleTerminal =
  tty && tty.isatty && tty.isatty(1) && env.TERM && env.TERM !== "dumb"
```

**Comment by jorgebucaran** [comment]
Yup, that's exactly what we're doing now. Should be fixed when you update your dependencies.

**Comment by from-nibly** [comment]
Ok well I think that would have actually solved my problem but it turns out postcss dropped colorette for nanocolors 12 hours ago :shrug:
