### ISSUE TITLE
Default exports break down in converted CJS version

### ISSUE THREAD

**Issue by kibertoad** [jorgebucaran/colorette#75]
See https://github.com/pinojs/pino-pretty/issues/237

`process["default"].env` is definitely incorrect. Looks like we should avoid using default imports here.

**Comment by kibertoad** [comment]
@jorgebucaran Wonder if we could be running CI on built CJS version somehow.

**Comment by kibertoad** [comment]
Duplicate of #73

**Comment by jorgebucaran** [comment]
Should be possible, let me check the docs.

**Comment by jorgebucaran** [comment]
@kibertoad Sorry, looking into your comment again, I'm not sure exactly what you mean. The CI runs the tests. We could look into adding a special test just for the CJS version, though. That what you were thinking?
