### ISSUE TITLE
Add Nano Colors mention as inspiration

### ISSUE THREAD

**Issue by ai** [jorgebucaran/colorette#78]
Recent [`!s` optimization](https://github.com/jorgebucaran/colorette/commit/b1d82b9a9204bdac19b6306c2426a179f4cd6c6b) was clearly backport from [Nano Colors](https://github.com/ai/nanocolors/commit/f421c2cc37504b51afd310ef297b52660327da3f). Can you add a note that Nano Colors was an inspiration for the project.

**Comment by ai** [comment]
> https://github.com/babel/babel/pull/13783#issuecomment-927258580

You edge case suggestions was very useful, but you didn’t mention `!s` fix [there](https://github.com/jorgebucaran/color-bench-test/pull/1). You didn’t create an initial boost, and you didn’t fix it to name yourself as author.

I most of the cases, I am OK with idea copying between projects. But in this case, I think I have the right to do another way and ask to mention me if you copied this performance boost. You may mention me in a way “Initially create in Nano Colors and then fixed by team work of me and Andrey Sitnik”.

**Comment by jorgebucaran** [comment]
I'm afraid you can't claim `!s` as your own invention. It's a pretty obvious fix by looking at the stack trace.

<img width="948" alt="Screen Shot 2021-09-26 at 18 07 14" src="https://user-images.githubusercontent.com/56996/134801287-83bdfed8-ed54-4f07-8d16-25898c340860.png">
 

I'm cool with borrowing ideas from each other too, of course.

**Comment by ai** [comment]
Anyway it was not did by you.

And it was a fix for initial my idea that `=== ''` compare is slow. Without that changes, this discussion would not be started.

**Comment by jorgebucaran** [comment]
Sorry, but I must disagree on behalf of the little programmer out there. You just can't take credit from _a_ `!s`. 

`!s` was the smallest change I had to make to avoid the explicit `s === undefined`, so I went with that. I could've reversed the expression just as well and not use `!s` at all:

```js
!(!s && (s === "" || s === undefined))
```
```js
s || (s !== "" && s !== undefined)
```
```js
s || !(s === "" || s === undefined)
```

They're all roughly equivalent and produce the same result. I'll tell you what, I'll switch to another one and close here.

**Comment by ai** [comment]
You lost the whole idea of optimization.

You saw from Nano Colors that `s !== "" && s !== undefined` is slow. You copied the fix of this slow part.

Now you are changing `!x` to `x` instead of do an honor thing and mention an author of original work.

**Comment by jorgebucaran** [comment]
I can't entertain you all day. You've produced no original work in this particular space and you can't take credit for a trivial `!s`, much less expect anyone to believe Colorette was inspired by nanocolors. I am glad, not for myself, but for OSS in general, that you admitted to restoring my `git` history and added me to your COPYRIGHT file, but now it's time to take a break.

**Comment by jorgebucaran** [comment]
Locked to prevent edits.
