### ISSUE TITLE
Regression in 2.x? Disable colors globally for tests

### ISSUE THREAD

**Issue by daKmoR** [jorgebucaran/colorette#87]
When running tests I want to disable all the colors for whoever is using it.
But my local CLI supports colors and it will auto-detect it as such.

what I did in my tests with 1.x

```js
import { options } from 'colorette';

describe('cli', () => {
  before(() => {
    // ignore colors in tests as most CIs won't support it
    options.enabled = false;
  });
  
  it('outputs status along the way', async () => {
    const { log } = await executeCli({ srcDir: 'fixtures/css-text' }, { captureLog: true });

    expect(log[0]).to.match(/👀 Finding all file in (.*) to render.../);  
  });
});
```

e.g. I disable the colors for the function `executeCli` - inside there I use `import { red } from 'colorette'`.

I don't see a way how to do this with the new API? even if I do `const { red } = createColors({ useColor: false })` in my test it will not effect the usage within `executeCli`.

**Comment by jorgebucaran** [comment]
Perhaps you could use `--no-color` or  `NO_COLOR=` from the CLI to disable color detection.

Or how about setting your own environment variable to tell your program how to behave?

```console
TEST_RUN= npm test
```
```js
import { createColors, isColorSupported } from "colorette"
import { env } from "process"

const { blue } = createColors({ useColor: isColorSupported && !env.TEST_RUN })

console.log(blue("To blue or not to blue?"))
```

Now, we detect if your environment supports color, so maybe you don't need to explicitly disable color to start with.

**Comment by jorgebucaran** [comment]
You could use `--no-color` or  `NO_COLOR=` from the CLI to disable color detection.

Or how about setting your own environment variable to tell your program how to behave?

```console
TEST_RUN= npm test
```
```js
import { createColors, isColorSupported } from "colorette"
import { env } from "process"

const { blue } = createColors({ useColor: isColorSupported && !env.TEST_RUN })

console.log(blue("To blue or not to blue?"))
```

Now, we already detect if your environment ([including your CI](https://github.com/jorgebucaran/colorette/blob/547fcf159db4a6e08fe8eaa76ff0b86c27d7d3c6/index.js#L13-L15)) supports color or not, so why go out of your way to disable it?

**Comment by jorgebucaran** [comment]
You could use `--no-color` or  `NO_COLOR=` from the CLI to disable color detection.

Or how about setting your own environment variable to tell your program how to behave?

```console
TEST_RUN= npm test
```
```js
import { createColors, isColorSupported } from "colorette"
import { env } from "process"

const { blue } = createColors({ useColor: isColorSupported && !env.TEST_RUN })

console.log(blue("To blue or not to blue?"))
```

Now, we already detect if your environment ([including your CI](https://github.com/jorgebucaran/colorette/blob/547fcf159db4a6e08fe8eaa76ff0b86c27d7d3c6/index.js#L13-L15)) supports color or not, so why go out of your way to disable it?

**Comment by daKmoR** [comment]
> Now, we already detect if your environment (including your CI) supports color or not, so why go out of your way to disable it?

because if I run the test locally it will fail... as I do have colors in my terminal (and I sure enjoy them)

so I could add it like this to the `package.json`

```
"scripts": {
  "test:node": "NO_COLOR= mocha \"packages/*/test-node/**/*.test.{ts,js,mjs,cjs}\" --timeout 5000 --reporter dot --exit",
}
```

and that works on mac... also on linux I assume... but are we sure that will work on windows, windows wsl 1, windows wsl 2?

**Comment by kibertoad** [comment]
you can use cross-env npm package for os-independent env setting

**Comment by daKmoR** [comment]
fair enough - thx 🤗
