### ISSUE TITLE
SvelteKit + colorette

### ISSUE THREAD

**Issue by jaclas** [jorgebucaran/colorette#89]
I get error in browser: "process is not defined"
I think the reason is in Vite and its handling of environment variables.

Similar problem:

https://stackoverflow.com/questions/71083110/vue-uncaught-referenceerror-process-is-not-defined

**Comment by kibertoad** [comment]
@jorgebucaran should we add check for process being defined?

**Comment by jorgebucaran** [comment]
Would that fix their issue? Sure. 👍
