### ISSUE TITLE
Wrong support detection on Windows

### ISSUE THREAD

**Issue by MartinKolarik** [jorgebucaran/colorette#90]
[This check](https://github.com/jorgebucaran/colorette/blob/main/index.js#L18) assumes that anything running on Windows supports colors, which is not true and results in garbage output sometimes. For example, the GitHub Desktop app doesn't support colors for its output for precommit hooks and it sets `env.TERM` to `dumb`. Comparing with supports-color package which handles this correctly, [this check](https://github.com/chalk/supports-color/blob/ee88ebcfca649233bb35c9b0db226059883a77b8/index.js#L89-L93) should probably have a higher priority than the platform.

**Comment by jorgebucaran** [comment]
Could you submit a patch or show us in our code what we'd need to do to support your use-case on Windows? Thanks.

**Comment by MartinKolarik** [comment]
Sure, I'll send a PR.
