### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'NO_COLOR' in undefined

### ISSUE THREAD

**Issue by jaclas** [jorgebucaran/colorette#94]
Unfortunately, the latest patch has again broken colorette's operation in the browser
![obraz](https://user-images.githubusercontent.com/17312717/173505940-f3c1f8d6-75ef-4175-a867-3eaf1df808bc.png)

**Comment by kibertoad** [comment]
@jorgebucaran that's what I was afraid for. let's revert

**Comment by jorgebucaran** [comment]
My bad, I'll fix this and push a fix ASAP.

**Comment by jorgebucaran** [comment]
My bad. I'll fix this and push a fix ASAP. 😅
